### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by iamjorgensen** [anderssv/smartthings-verisure#2]
Hi, 

Verisure integration works perfect for a while and then suddenly no more updates - no sensors upated for 5 days.  Is this a known issue? I can be helpful with logs if you tell me what is needed to investigate :smile: 

Brgds
Christian

**Comment by orecus** [comment]
That is very strange! Do you see any errors in the ”Live Log” area in Smartthings?

**Comment by iamjorgensen** [comment]
No there is no "life" so to speak. I have let the live log run for some hours now but there is no logs related to verisure components. All verisure components have status "inactive" in device list (last activity = 5 days ago)

**Comment by anderssv** [comment]
If there are no logs whatsoever I'm afraid there's not much we can do. A couple of things to try:

- Go into the settings for the application and press save. Do you see any log entries when you do this? Do you see any log entries after trying this?
- If the above doesn't work, try removing the app and then re-install it.

Which version are you using?

**Comment by iamjorgensen** [comment]
Hi
Going in and just saving the app sparked things to life again!

Version is 0.2.1

Brgds
Christian

**Comment by anderssv** [comment]
Good to hear. Every time the app saves the settings a schedule is registered with the SmartThings platform. This schedule is indefinite so it should run forever. But for some reason the platform wiped your schedule, and re-saving the settings added it back again. 

Don't think we can do anything about that, but anyone else having this problem feel free to add a comment so we track the problem.

**Comment by iamjorgensen** [comment]
Thanks for your help Anders, I have also updated to the latest version of your code. Thanks for your efforts in connecting Verisure to smartthings - really great!!!
