### ISSUE TITLE
Problem with installation.

### ISSUE THREAD

**Issue by ocisyd** [anderssv/smartthings-verisure#6]
Hi. I tried to install the integration but get this message "physicalgraph.exception.NotFoundException: Page Not Found".

Someone who knows?

**Comment by balajibalasa** [comment]
I followed all the step mentioned in the I read me , when I go to SmartThings app I do not see Verisure in the smart app list , am I missing some thing , please help

**Comment by anderssv** [comment]
Sorry guys, I can't help you with these kinds of errors. Try and remove everything and do the steps agian.
